;;; Elfeed score file     -*- lisp -*-
(
 ("link"
  (:text "/football/" :value -500 :type s)
  (:text "/tv-and-radio/" :value -200 :type s)
  (:text "/commentisfree/" :value -100 :type s)
  (:text "/australia-news/" :value -300 :type s)
  (:text "/culture/" :value -100 :type s)
  (:text "/audio/" :value -100 :type s)
  (:text "/money/" :value 200 :type s)
  (:text "/environment/" :value 100 :type s)
  (:text "/global-development/" :value 200 :type s)
  (:text "/world/" :value 100 :type s)
  (:text "/society/" :value -100 :type s)
  (:text "/food/" :value -100 :type s)
  (:text "/us-news/" :value -100 :type s)
  (:text "/fashion/" :value -300 :type s)
  (:text "/artanddesign/" :value -100 :type s)
  (:text "/film/" :value -100 :type s)
  (:text "/books/" :value -100 :type s)
  (:text "/travel/" :value -100 :type s)
  (:text "/sport/" :value -200 :type s)
  (:text "altalex.com" :value 300 :type s)
  (:text "offerte-lavoro" :value 400 :type s)
  (:text "/charlie/" :value -200 :type s)
  (:text "https://www.ilpost.it/newsletter/" :value -200 :type s)
  (:text "https://www.ft.com" :value 300 :type s)
  (:text "https://www.ilpost.it/episodes/" :value -200 :type s)
  )
 ("tag"
  (:tags (t . tuebingen) :value 300)
  (:tags (t . opinion) :value -100)
  (:tags (t . emacs) :value -100)
  (:tags (t . sport) :value -500)
  (:tags (t . science) :value 100)
  )
 ("title"
  (:text "macOS" :value -200 :type S)
  (:text "Le canzoni" :value -300 :type s)
  (:text "Peanuts" :value -300 :type s)
  (:text "assorted links" :value +150 :type s)
  (:text "Italy" :value +150 :type s)
  (:text "chiusure" :value +100 :type s)
  (:text "Germany" :value +100 :type s)
  (:text "Football" :value -100 :type s)
  (:text "WSJ" :value +200 :type S)
  (:text "Elon" :value -100 :type S)
  (:text "Sacha Chua" :value +50 :type S)
  )
 ("title-or-content"
  (:text "Pro Patria" :title-value -500 :content-value -500 :type s)
  (:text "alaska" :title-value 100 :content-value 100 :type s)
  (:text "OECD" :title-value 100 :content-value 120 :type S)
  (:text "migrant" :title-value 100 :content-value 250 :type s)
  (:text "fusion energy" :title-value 100 :content-value 200 :type s)
  (:text "nuclear" :title-value 100 :content-value 200 :type s)
  (:text "cosa fare nel weekend" :title-value 200 :content-value 150 :type s)
  (:text "Was geht am Wochenende" :title-value 200 :content-value +200 :type s)
  (:text "robot" :title-value 300 :content-value +400 :type s)
  (:text "air show" :title-value 300 :content-value +400 :type s)
  (:text "Meloni" :title-value 100 :content-value +100 :type s)
  (:text "A9" :title-value nil :content-value nil :type s)
  )
 ("feed"
  (:text "Planet Emacslife" :value 100 :type S :attr t)
  (:text "jwz" :value -100 :type S :attr t)
  (:text "OECD" :value 200 :type S :attr t)
  (:text "Hacker News" :value 100 :type S :attr t)
  (:text "Disinformatico" :value 200 :type S :attr t)
  (:text "The Intercept" :value 300 :type S :attr t)
  (:text "GuardianOpinion" :value -100 :type S :attr t)
  (:text "Guardian" :value 100 :type S :attr t)
  (:text "Marginal Revolution" :value 200 :type S :attr t)
  (:text "POLITICO" :value 200 :type S :attr t)
  (:text "Eco Risveglio" :value 100 :type S :attr t)
  (:text "VareseNews" :value 200 :type S :attr t :tags (t . sport))
  (:text "VareseNews" :value -600 :type S :attr t)
  (:text "euro|topics" :value 200 :type S :attr t)
  (:text "WSJ.com: World News" :value 300 :type S :attr t)
  (:text "Il Post" :value 400 :type S :attr t)
  )
)